package com.material.backend.mapper;

import com.material.backend.model.Rights;
import com.material.backend.model.RightsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    long countByExample(RightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int deleteByExample(RightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int insert(Rights row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int insertSelective(Rights row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    List<Rights> selectByExampleWithRowbounds(RightsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    List<Rights> selectByExample(RightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    Rights selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByExampleSelective(@Param("row") Rights row, @Param("example") RightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByExample(@Param("row") Rights row, @Param("example") RightsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByPrimaryKeySelective(Rights row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByPrimaryKey(Rights row);
}