package com.material.backend.mapper;

import com.material.backend.model.Roles;
import com.material.backend.model.RolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    long countByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int deleteByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int insert(Roles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int insertSelective(Roles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    List<Roles> selectByExampleWithRowbounds(RolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    List<Roles> selectByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    Roles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByExampleSelective(@Param("row") Roles row, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByExample(@Param("row") Roles row, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByPrimaryKeySelective(Roles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByPrimaryKey(Roles row);
}