package com.material.backend.mapper;

import com.material.backend.model.UserRoles;
import com.material.backend.model.UserRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    long countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int insert(UserRoles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int insertSelective(UserRoles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    List<UserRoles> selectByExampleWithRowbounds(UserRolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    List<UserRoles> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    UserRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByExampleSelective(@Param("row") UserRoles row, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByExample(@Param("row") UserRoles row, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByPrimaryKeySelective(UserRoles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    int updateByPrimaryKey(UserRoles row);
}