package com.material.backend.model;

import java.util.Date;

public class Rights {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.id
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_name
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String rightsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_desc
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String rightsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_state
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Boolean rightsState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_type
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String rightsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_path
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String rightsPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.pid
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.level
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.created_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.updated_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_method
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String rightsMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights_icon
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String rightsIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.id
     *
     * @return the value of rights.id
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.id
     *
     * @param id the value for rights.id
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_name
     *
     * @return the value of rights.rights_name
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRightsName() {
        return rightsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_name
     *
     * @param rightsName the value for rights.rights_name
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsName(String rightsName) {
        this.rightsName = rightsName == null ? null : rightsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_desc
     *
     * @return the value of rights.rights_desc
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRightsDesc() {
        return rightsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_desc
     *
     * @param rightsDesc the value for rights.rights_desc
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsDesc(String rightsDesc) {
        this.rightsDesc = rightsDesc == null ? null : rightsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_state
     *
     * @return the value of rights.rights_state
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Boolean getRightsState() {
        return rightsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_state
     *
     * @param rightsState the value for rights.rights_state
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsState(Boolean rightsState) {
        this.rightsState = rightsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_type
     *
     * @return the value of rights.rights_type
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRightsType() {
        return rightsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_type
     *
     * @param rightsType the value for rights.rights_type
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsType(String rightsType) {
        this.rightsType = rightsType == null ? null : rightsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_path
     *
     * @return the value of rights.rights_path
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRightsPath() {
        return rightsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_path
     *
     * @param rightsPath the value for rights.rights_path
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsPath(String rightsPath) {
        this.rightsPath = rightsPath == null ? null : rightsPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.pid
     *
     * @return the value of rights.pid
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.pid
     *
     * @param pid the value for rights.pid
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.level
     *
     * @return the value of rights.level
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.level
     *
     * @param level the value for rights.level
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.created_at
     *
     * @return the value of rights.created_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.created_at
     *
     * @param createdAt the value for rights.created_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.updated_at
     *
     * @return the value of rights.updated_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.updated_at
     *
     * @param updatedAt the value for rights.updated_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_method
     *
     * @return the value of rights.rights_method
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRightsMethod() {
        return rightsMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_method
     *
     * @param rightsMethod the value for rights.rights_method
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsMethod(String rightsMethod) {
        this.rightsMethod = rightsMethod == null ? null : rightsMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights_icon
     *
     * @return the value of rights.rights_icon
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRightsIcon() {
        return rightsIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights_icon
     *
     * @param rightsIcon the value for rights.rights_icon
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRightsIcon(String rightsIcon) {
        this.rightsIcon = rightsIcon == null ? null : rightsIcon.trim();
    }
}