package com.material.backend.model;

import java.util.Date;

public class RoleRights {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights.id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights.role_id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights.rights_id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    private Integer rightsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights.created_at
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights.updated_at
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights.id
     *
     * @return the value of role_rights.id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights.id
     *
     * @param id the value for role_rights.id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights.role_id
     *
     * @return the value of role_rights.role_id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights.role_id
     *
     * @param roleId the value for role_rights.role_id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights.rights_id
     *
     * @return the value of role_rights.rights_id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public Integer getRightsId() {
        return rightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights.rights_id
     *
     * @param rightsId the value for role_rights.rights_id
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public void setRightsId(Integer rightsId) {
        this.rightsId = rightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights.created_at
     *
     * @return the value of role_rights.created_at
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights.created_at
     *
     * @param createdAt the value for role_rights.created_at
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights.updated_at
     *
     * @return the value of role_rights.updated_at
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights.updated_at
     *
     * @param updatedAt the value for role_rights.updated_at
     *
     * @mbg.generated Sun May 15 23:30:03 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}