package com.material.backend.model;

import java.util.Date;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_name
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_desc
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_state
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Boolean roleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.created_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.updated_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_name
     *
     * @return the value of roles.role_name
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_name
     *
     * @param roleName the value for roles.role_name
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_desc
     *
     * @return the value of roles.role_desc
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_desc
     *
     * @param roleDesc the value for roles.role_desc
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_state
     *
     * @return the value of roles.role_state
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Boolean getRoleState() {
        return roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_state
     *
     * @param roleState the value for roles.role_state
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setRoleState(Boolean roleState) {
        this.roleState = roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.created_at
     *
     * @return the value of roles.created_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.created_at
     *
     * @param createdAt the value for roles.created_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.updated_at
     *
     * @return the value of roles.updated_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.updated_at
     *
     * @param updatedAt the value for roles.updated_at
     *
     * @mbg.generated Fri May 20 17:45:33 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}